name: Testing your PR
on:
  pull_request:
    branches:
      - master

jobs:  
  pytest:
    name: pytest
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, pypy2, pypy3]
        os: [ubuntu-latest]
      fail-fast: False
      include:
        - os: ubuntu-latest
          python-version: 3.7
          run-official: True
    steps:
      - uses: actions/checkout@v1
      - name: Initialize vendored libs
        run: 
          git submodule update --init --recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U codecov pytest-cov
          pip install ujson
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Test with pytest (no coverage)
        run: |
          pytest -v -m nocoverage
      - name: Test with pytest (coverage)
        run: |
          pytest -v -m "not nocoverage"

      - name: Compare to official api
        run: |
          pytest -v tests/test_official.py

      - run: |
          if [ "$CODECOV_TOKEN" != "" ]; then
             coverage combine
             codecov -F Github -t $CODECOV_TOKEN
          fi
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
